environment:
  matrix:
    - PYTHON: "C:\\Python27"

build: false

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -r requirements.txt

build_script:
  - python setup.py install

test_script:
  - tox
